version: "3"
services:
  sample:
    build: .
    volumes:
# Linux
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/workspace/extend_costmap_2d
    environment:
# Win
      - DISPLAY=host.docker.internal:0.0
# Linux
      # - DISPLAY=:0
    privileged: true
    tty: true
